name: mirrorchyan_uploading

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'OneDragon-Anything' && (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Upload Full Package
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "ZenlessZoneZero-OneDragon-*-Full-Environment.zip"
          mirrorchyan_rid: ZZZ-OneDragon

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: OneDragon-Anything
          repo: ZenlessZoneZero-OneDragon
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

      - name: Upload Launcher
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-launcher
          filename: "ZenlessZoneZero-OneDragon-Launcher.zip"
          mirrorchyan_rid: ZZZ-OneDragon

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: OneDragon-Anything
          repo: ZenlessZoneZero-OneDragon
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: win
          arch: x86_64
